name: Health Report Action

on:
  workflow_dispatch:
    inputs:
      sleep:
        description: 'Whether to wait for a random time'
        required: false
        default: false
        type: boolean
  schedule:
    - cron: '0 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: Run Script Auto
        if: ${{ github.event.inputs.sleep == '' }}
        env:
          NJU_USERNAME: ${{ secrets.username }}
          NJU_PASSWORD: ${{ secrets.password }}
          LOCATION_INFO_FROM: ${{ secrets.location_info_from }}
          CURR_LOCATION: ${{ secrets.location }}
          COVID_TEST_METHOD: ${{ secrets.covid_test_method }}
          SLEEP: true
        run: |
          python run.py
      - name: Run Script Manually
        if: ${{ github.event.inputs.sleep != '' }}
        env:
          NJU_USERNAME: ${{ secrets.username }}
          NJU_PASSWORD: ${{ secrets.password }}
          LOCATION_INFO_FROM: ${{ secrets.location_info_from }}
          CURR_LOCATION: ${{ secrets.location }}
          COVID_TEST_METHOD: ${{ secrets.covid_test_method }}
          SLEEP: ${{ github.event.inputs.sleep }}
        run: |
          python run.py
      - name: Send mail
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.mail_username }}
          password: ${{ secrets.mail_password }}
          subject: 每日打卡信息
          body:  file://email.txt
          to: ${{ secrets.receive_email }}
          from: GitHub Actions
